services:
  notebook:
    image: logus2k/noted
    container_name: noted
    build: .
    pull_policy: never
    ports:
      - "8123:8123"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
