services:
  notebook:
    image: logus2k/noted
    container_name: noted
    build: .
    ports:
      - "8123:8123"
    volumes:
      - ./data:/app/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
